variable "hcp_client_id" {}
variable "hcp_client_secret" {}
variable "hcp_project_id" {}
variable "hvn_id" {}
variable "hvn_region" {}
variable "hvn_cidr" {}
variable "hvn_cloud_provider" {}
variable "vault_cluster_id" {}
variable "vault_namespace" {}
variable "gemini_api_key" {}
variable "prisma_airs_api_key" {}
variable "prisma_airs_profile" {}
variable "db_port" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "db_host" {}