apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-chatbot
  labels:
    app: ai-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-chatbot
  template:
    metadata:
      labels:
        app: ai-chatbot
    spec:
      containers:
        - name: ai-chatbot
          # REPLACE this with your pushed image (set via Terraform or replace here)
          image: REPLACE_WITH_REGISTRY/ai-chatbot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: GEMINI_API_KEY
            - name: PRISMA_AIRS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: PRISMA_AIRS_API_KEY
            - name: PRISMA_AIRS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: chatbot-secrets
                  key: PRISMA_AIRS_PROFILE
          readinessProbe:
            httpGet:
              path: /token-suffix
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /token-suffix
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 30

