apiVersion: v1
kind: Service
metadata:
  name: ai-chatbot-svc
  labels:
    app: ai-chatbot
spec:
  type: ClusterIP
  selector:
    app: ai-chatbot
  ports:
    - name: http
      port: 80
      targetPort: 5000

