---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: trusted-ai
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  annotations:
    kubernetes.io/service-account.name: vault-sa
  namespace: trusted-ai
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vault-sa
    namespace: trusted-ai
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: trusted-ai
spec:
  namespace: admin/trusted-ai-secrets
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: ai-chatbot-role
    serviceAccount: chatbot
    audiences:
      - https://kubernetes.default.svc
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ai-chatbot-secret
  namespace: trusted-ai
spec:
  namespace: admin/trusted-ai-secrets
  type: kv-v2
  mount: kv
  path: chatbot
  destination:
    name: chatbotkv
    create: true
  refreshAfter: 2s
  vaultAuthRef: vault-auth
  syncConfig:
    instantUpdates: true
  rolloutRestartTargets:
    - kind: Deployment
      name: ai-chatbot
    - kind: Deployment
      name: ai-agent
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: ai-agent-secret
  namespace: trusted-ai
spec:
  namespace: admin/trusted-ai-secrets
  mount: postgres
  path: creds/ai-agent-app
  destination:
    create: true
    name: agentkv
    overwrite: true
  refreshAfter: "30s"
  rolloutRestartTargets:
    - kind: Deployment
      name: ai-agent
  vaultAuthRef: vault-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chatbot
  namespace: trusted-ai
  annotations:
    vault.hashicorp.com/alias-metadata-AppName: "chatbot"
