apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: chatbot-auth
  namespace: default
spec:
  vaultConnectionRef: vault-connection
  method: jwt
  mount: "${vault_jwt_auth_backend.demo_jwt_auth.path}"
  namespace: "${var.vault_namespace}"
  allowedNamespaces: ["${kubernetes_namespace_v1.demo_static_app.metadata[0].name}"]
  storageEncryption:
    keyName: "${var.vso_transit_key_name}"
    mount: "${var.vso_transit_path}"
  jwt:
    audiences:
      - "${kubernetes_namespace_v1.demo_static_app.metadata[0].name}"
    role: "${vault_jwt_auth_backend_role.static_app_role.role_name}"
    serviceAccount: chatbot-sa
    tokenExpirationSeconds: 600